"Name: \PR:RFFOBR_A\FO:DATEI_SCHLIESSEN\SE:END\EI
ENHANCEMENT 0 ZEIFI_AUTBANC_GRAVAR_COB_A.
* FI AR 141 - Automatização bancária VAN FINNET
  INCLUDE zfie_autbanc_gravar_cob_a IF FOUND.
ENDENHANCEMENT.
