"Name: \PR:ZRFFOBR_U\FO:DATEI_SCHLIESSEN\SE:END\EI
ENHANCEMENT 0 ZEIFI_AUTBANC_GRAVAR_COB_U.
* FI AR 141 - Automatização bancária VAN FINNET
  INCLUDE zfie_autbanc_gravar_cob IF FOUND.
ENDENHANCEMENT.
