*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVFI_AUTBANC_LOG................................*
FORM GET_DATA_ZVFI_AUTBANC_LOG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTFI_AUTBANC_LOG WHERE
(VIM_WHERETAB) .
    CLEAR ZVFI_AUTBANC_LOG .
ZVFI_AUTBANC_LOG-CLIENT =
ZTFI_AUTBANC_LOG-CLIENT .
ZVFI_AUTBANC_LOG-CODIGO =
ZTFI_AUTBANC_LOG-CODIGO .
ZVFI_AUTBANC_LOG-NOME =
ZTFI_AUTBANC_LOG-NOME .
ZVFI_AUTBANC_LOG-TIPO =
ZTFI_AUTBANC_LOG-TIPO .
ZVFI_AUTBANC_LOG-CHAVE_BREVE =
ZTFI_AUTBANC_LOG-CHAVE_BREVE .
ZVFI_AUTBANC_LOG-MSGTYPE =
ZTFI_AUTBANC_LOG-MSGTYPE .
ZVFI_AUTBANC_LOG-DIRETORIO =
ZTFI_AUTBANC_LOG-DIRETORIO .
ZVFI_AUTBANC_LOG-MESSAGE =
ZTFI_AUTBANC_LOG-MESSAGE .
<VIM_TOTAL_STRUC> = ZVFI_AUTBANC_LOG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_AUTBANC_LOG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_AUTBANC_LOG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_AUTBANC_LOG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_AUTBANC_LOG WHERE
  CODIGO = ZVFI_AUTBANC_LOG-CODIGO .
    IF SY-SUBRC = 0.
    DELETE ZTFI_AUTBANC_LOG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTFI_AUTBANC_LOG WHERE
  CODIGO = ZVFI_AUTBANC_LOG-CODIGO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTFI_AUTBANC_LOG.
    ENDIF.
ZTFI_AUTBANC_LOG-CLIENT =
ZVFI_AUTBANC_LOG-CLIENT .
ZTFI_AUTBANC_LOG-CODIGO =
ZVFI_AUTBANC_LOG-CODIGO .
ZTFI_AUTBANC_LOG-NOME =
ZVFI_AUTBANC_LOG-NOME .
ZTFI_AUTBANC_LOG-TIPO =
ZVFI_AUTBANC_LOG-TIPO .
ZTFI_AUTBANC_LOG-CHAVE_BREVE =
ZVFI_AUTBANC_LOG-CHAVE_BREVE .
ZTFI_AUTBANC_LOG-MSGTYPE =
ZVFI_AUTBANC_LOG-MSGTYPE .
ZTFI_AUTBANC_LOG-DIRETORIO =
ZVFI_AUTBANC_LOG-DIRETORIO .
ZTFI_AUTBANC_LOG-MESSAGE =
ZVFI_AUTBANC_LOG-MESSAGE .
    IF SY-SUBRC = 0.
    UPDATE ZTFI_AUTBANC_LOG ##WARN_OK.
    ELSE.
    INSERT ZTFI_AUTBANC_LOG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_AUTBANC_LOG-UPD_FLAG,
STATUS_ZVFI_AUTBANC_LOG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFI_AUTBANC_LOG.
  SELECT SINGLE * FROM ZTFI_AUTBANC_LOG WHERE
CODIGO = ZVFI_AUTBANC_LOG-CODIGO .
ZVFI_AUTBANC_LOG-CLIENT =
ZTFI_AUTBANC_LOG-CLIENT .
ZVFI_AUTBANC_LOG-CODIGO =
ZTFI_AUTBANC_LOG-CODIGO .
ZVFI_AUTBANC_LOG-NOME =
ZTFI_AUTBANC_LOG-NOME .
ZVFI_AUTBANC_LOG-TIPO =
ZTFI_AUTBANC_LOG-TIPO .
ZVFI_AUTBANC_LOG-CHAVE_BREVE =
ZTFI_AUTBANC_LOG-CHAVE_BREVE .
ZVFI_AUTBANC_LOG-MSGTYPE =
ZTFI_AUTBANC_LOG-MSGTYPE .
ZVFI_AUTBANC_LOG-DIRETORIO =
ZTFI_AUTBANC_LOG-DIRETORIO .
ZVFI_AUTBANC_LOG-MESSAGE =
ZTFI_AUTBANC_LOG-MESSAGE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_AUTBANC_LOG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_AUTBANC_LOG-CODIGO TO
ZTFI_AUTBANC_LOG-CODIGO .
MOVE ZVFI_AUTBANC_LOG-CLIENT TO
ZTFI_AUTBANC_LOG-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTFI_AUTBANC_LOG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTFI_AUTBANC_LOG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTFI_AUTBANC_LOG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
