interface ZCLFI_II_SI_CONTABILZACAO_PROC
  public .


  methods SI_CONTABILZACAO_PROCESSAMENTO
    importing
      !INPUT type ZCLFI_MT_PROCESSAMENTO_REVERSA
    exporting
      !OUTPUT type ZCLFI_MT_PROCESSAMENTO_REVERS1
    raising
      ZCLFI_CX_FMT_CONTABILIZACAO .
endinterface.
